### ISSUE TITLE
Username should be the cleaned username

### ISSUE THREAD

**Issue by nickvergessen** [tas2580/phpBB-3.1-Failed-logins#4]
Uppercase etc should not make a difference.
There is a method for it ;)

**Comment by tas2580** [comment]
Fixed on  https://github.com/tas2580/phpBB-3.1-Failed-logins/commit/fdf03479e68179c904b70803e019f5cbd96a4529

**Comment by Galixte** [comment]
Hi @tas2580,

there is an answer here: https://github.com/tas2580/phpBB-3.1-Failed-logins/commit/fdf03479e68179c904b70803e019f5cbd96a4529#commitcomment-11684452.

**Comment by nickvergessen** [comment]
https://github.com/phpbb/phpbb/blob/3.1.x/phpBB/includes/functions_user.php#L177
