### ISSUE TITLE
DB column should be UINT instead of `INT:`

### ISSUE THREAD

**Issue by nickvergessen** [tas2580/phpBB-3.1-Failed-logins#6]
`INT:` without a size causes troubles on some DBMS

**Comment by tas2580** [comment]
https://github.com/tas2580/phpBB-3.1-Failed-logins/commit/fdf03479e68179c904b70803e019f5cbd96a4529

**Comment by nickvergessen** [comment]
You still have the trailing `:`

**Comment by tas2580** [comment]
Oh man, you have always something to complain about ;)

Thanks a lot, fixed.
