### ISSUE TITLE
Effectively installed check checks wrong config

### ISSUE THREAD

**Issue by nickvergessen** [tas2580/phpBB-3.1-Failed-logins#7]
`return isset($this->config['failedlogins_version']) && version_compare($this->config['pss_version'], '0.1.1', '>=');`

Also instead of checking for the config, I'd check whether the column actually exists.

**Comment by tas2580** [comment]
Fixed on https://github.com/tas2580/phpBB-3.1-Failed-logins/commit/fdf03479e68179c904b70803e019f5cbd96a4529
